# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def shared_pod
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'UtilityKit',:git=>'https://github.com/utills/UtilityKit.git'
  pod 'Firebase/Auth'
end

target 'Solute' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  shared_pod
  # Pods for Solute

  target 'SoluteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SoluteUITests' do
    # Pods for testing
  end

end

target 'BharatBandhu' do
  use_frameworks!
  shared_pod
end
