//
//  Keys.swift
//  Solute
//
//  Created by Vivek Singh on 11/12/22.
//

import Foundation
class Key{
    public static let encryptionIV = "EncryptionIV"
    public static let encryptionSalt = "EncryptionSalt"
    public static let isAccepted = "IsAccepted"
    public static let loginDetails = "UserLoginDetails"
    public static let content = "Content"
    public static let contentType = "ContentType"
    public static let allContacts = "AllContacts"
    public static let conversationID = "ConversationID"
    public static let lastMessageDetails = "lastMessageDetails"
    public static let time = "Time"
    public static let sentRequest = "SentRequest"
    public static let receivedRequest = "ReceivedRequest"
    public static let blockList = "BlockList"
    public static let lastSeen = "LastSeen"
    public static let versionName = "VersionName"
    
    public static let id = "ID"
    public static let _id = "_id"
    
    public static let payload = "Payload"
    public static let message = "Message"
    public static let messageID = "MessageID"
    public static let adminUsers = "AdminUsers"
    public static let adminUserProfiles = "AdminUserProfiles"
    public static let participants = "Participants"
    public static let participantsProfiles = "ParticipantProfiles"
    public static let groupName = "GroupName"
    public static let groupDescription = "GroupDescription"
    public static let ownerUserID = "OwnerUserID"
    public static let employeeUserID = "EmployeeUserID"
    public static let employeeID = "EmployeeID"
    public static let attendanceDate = "AttendanceDate"
    public static let isPresent = "IsPresent"
    
    public static let userId = "UserID"
    public static let businessID = "BusinessID"
    public static let businessTypeID = "BusinessTypeID"
    public static let business = "Business"
    public static let customer = "Customer"
    public static let customerName = "CustomerName"
    public static let customerID = "CustomerID"
    public static let customerMobile = "CustomerMobile"
    public static let vehicleNumber = "VehicleNumber"
    public static let IGST = "IGST"
    public static let CGST = "CGST"
    public static let SGST = "SGST"
    public static let VAT = "VAT"
    public static let CESS = "CESS"
    public static let tax = "Tax"
    public static let MRP = "MRP"
    public static let price = "Price"
    public static let finalPrice = "FinalPrice"
    public static let costPrice = "CostPrice"
    public static let saleDate = "SaleDate"
    public static let discount = "Discount"
    public static let instantDiscount = "InstantDiscount"
    
    public static let productID = "ProductID"
    public static let productName = "ProductName"
    public static let product = "Product"
    public static let roomId = "ROOM_ID"
    public static let mobileNumber = "MobileNumber"
    public static let emailId = "EmailID"
    public static let password = "Password"
    public static let deviceId = "DeviceID"
    public static let countryCode = "CountryCode"
    public static let fcmToken = "FCMToken"
    public static let created = "Created"
    public static let updated = "Updated"
    public static let profilePicture = "ProfilePicture"
    public static let friendList = "FriendList"
    public static let profile = "Profile"
    public static let profiles = "Profiles"
    public static let createdAt = "CreatedAt"
    public static let updatedAt = "UpdatedAt"
    public static let numberOfDays = "NumberOfDays"
    public static let creator = "Creator"
    public static let transactions = "Transactions"
    public static let sales = "Sales"
    public static let salesID = "SalesID"
    public static let quantity = "Quantity"
    public static let comment = "Comment"
    
    
    public static let to = "to"
    public static let notification = "notification"
    public static let title = "Title"
    public static let body = "body"
    public static let data = "Data"
    public static let imageData = "ImageData"
    public static let authorization = "Authorization"
    public static let senderId = "SenderID"
    public static let receiverId = "ReceiverID"
    public static let senderFCM = "SenderFCM"
    public static let receiverFCM = "ReceiverFCM"
    public static let type = "Type"
    public static let isRead = "IsRead"
    public static let isSent = "IsSent"
    public static let isReceived = "IsReceived"
    public static let isUploaded = "IsUploaded"
    public static let isDownloaded = "IsDownloaded"
    public static let isTyping = "IsTyping"
    public static let invoice = "Invoice"
    public static let invoiceNumber = "InvoiceNumber"
    
    public static let userCredentials = "user_credentials"
    public static let trainerCredentials = "TrainerCredentials"
    public static let membershipDetails = "membership_details"
    public static let barcode = "Barcode"
    public static let height = "height"
    public static let weight = "weight"
    public static let aadhaarNumber = "aadhaar_number"
    
    public static let dateOfBirth = "date_of_birth"
    public static let address = "Address"
    public static let zipCode = "zip_code"
    public static let currentGymId = "current_gym_id"
    public static let joiningDate = "current_gym_joining_date"
    public static let startDate = "StartDate"
    public static let endDate = "EndDate"
    public static let dueDate = "DueDate"
    public static let priority = "Priority"
    public static let lastGymId = "last_gym_id"
    public static let date = "Date"
    
    
    public static let gymId = "gym_id"
    public static let gstNumber = "gst_number"
    public static let workingDays = "working_days"
    public static let workingDay = "working_day"
    public static let hours = "Hours"
    public static let panNumber = "pan_number"
    
    //For workout
    public static let name = "Name"
    public static let gender = "Gender"
    public static let status = "Status"
    public static let statusDescription = "StatusDescription"
    public static let imageUrl = "ImageURL"
    public static let image = "Image"
    
    public static let model = "model"
    public static let mode = "Mode"
    public static let description = "Description"
    public static let manageInventory = "ManageInventory"
    public static let taxIncluded = "TaxIncluded"
    public static let instruction = "Instruction"
    public static let steps = "Steps"
    public static let repetition = "Repetition"
    public static let category = "Category"
    public static let categoryId = "CategoryID"
    public static let subCategoryID = "SubCategoryID"
    public static let toUserId = "ToUserID"
    public static let isGroup = "ISGroup"
    public static let fromUserId = "FromUserID"
    public static let friendRequestId = "FriendRequestID"
    public static let fromDetails = "fromDetails"
    public static let toDetails = "toDetails"
    public static let fromUser = "FromUser"
    public static let toUser = "ToUser"
    public static let language = "Language"
    public static let dialCode = "DialCode"
    
    public static let workout = "Workout"
    public static let sets = "Sets"
    
    public static let workoutPlan = "WorkoutPlan"
    
    
    public static let muscleSecondary = "MusclesSecondary"
    public static let musclePrimary = "MusclesPrimary"
    public static let equipment = "Equipment"
    public static let exercise = "Exercise"
    public static let exerciseID = "ExerciseID"
    
    public static let sentTime = "SentTime"
    public static let deliveredTime = "DeliveredTime"
    public static let readTime = "ReadTime"
    public static let acceptedTime = "AcceptedTime"
    public static let search = "search"
    
    public static let dynamicLink = "DynamicLink"
    
    public static let companyId = "CompanyID"
    public static let company = "Company"
    public static let designation = "Designation"
    public static let designationID = "DesignationID"
    public static let technologies = "Technologies"
    public static let working = "Working"
    public static let fromDate = "FromDate"
    public static let toDate = "ToDate"
    public static let taskDetails = "TaskDetails"
    public static let taskID = "TaskID"
    public static let taskAttachmentID = "TaskAttachmentID"
    public static let fileURL = "FileURL"
    
    public static let lastSyncDate = "LastSyncDate"
}
