
module.exports = Object.freeze({
    "ACCEPT_EMPLOYEE_CONNECTION_REQUEST":"ACCEPT_EMPLOYEE_CONNECTION_REQUEST",
    "REJECT_EMPLOYEE_CONNECTION_REQUEST":"REJECT_EMPLOYEE_CONNECTION_REQUEST",
    "EMPLOYEE_CONNECTION_REQUEST_ACCEPTED":"EMPLOYEE_CONNECTION_REQUEST_ACCEPTED",
    "EMPLOYEE_CONNECTION_REQUEST_REJECTED":"EMPLOYEE_CONNECTION_REQUEST_REJECTED",
    "CREATE_EMPLOYEE_CONNECTION_REQUEST":"CREATE_EMPLOYEE_CONNECTION_REQUEST"
});