package com.utilitykit.SocketUtill

enum class SocketEvent(val value: String)
{
    connect("CONNECT"),
    connection("CONNECTION"),
    disconnect("DISCONNECT"),
    joinRoom("JOIN_ROOM"),
    getEncryptionKeys("GET_ENCRYPTION_KEYS"),
    isOnline("IS_ONLINE"),
    onEvent("ON_EVENT"),
    authenticate("AUHTENTICATE"),
    updateProfile("UPDATE_PROFILE"),
    sendMessage("SEND_MESSAGE"),
    sendTaskMessage("SEND_TASK_MESSAGE"),
    getAllMessage("GET_ALL_MESSAGE"),
    onMessage("ON_MESSAGE"),
    onTaskMessage("ON_TASK_MESSAGE"),
    updateMessage("UPDATE_MESSAGE"),
    messageReceived("MESSAGE_RECEIVED"),
    messageRead("MESSAGE_READ"),
    typing("TYPING"),
    previousChats("PREVIOUS_CHATS"),
    onPreviousChats("ON_PREVIOUS_CHATS"),
    newChats("NEW_CHATS"),
    updateDeliveryStatus("UPDATE_DELIVERY_STATUS"),
    updateReadStatus("UPDATE_READ_STATUS"),
    findUsers("FIND_USERS"),
    getAllConversation("GET_ALL_CONVERSATION"),
    createConversation("CREATE_CONVERSATION"),
    createGroup("CREATE_GROUP"),
    deleteGroup("DELETE_GROUP"),
    updateGroup("UPDATE_GROUP"),
    updateGroupName("UPDATE_GROUP_NAME"),
    updateGroupDescription("UPDATE_GROUP_DESCRIPTION"),
    updateGroupImage("UPDATE_GROUP_IMAGE"),
    findCompanyByName("FIND_COMPANY_BY_NAME"),
    findDesignationByName("FIND_DESIGNATION_BY_NAME"),
    findTechnologyByName("FIND_TECHNOLOGY_BY_NAME"),
    createExperience("CREATE_EXPERIENCE"),
    getAllExperience("GET_ALL_EXPERIENCE"),
    updateContacts("UPDATE_CONTACTS"),
    retriveContacts("RETRIVE_CONTACTS"),
    createTask("CREATE_TASK"),
    updateTask("UPDATE_TASK"),
    updateTaskStatus("UPDATE_TASK_STATUS"),
    updateTaskPriority("UPDATE_TASK_PRIORITY"),
    getAllTask("GET_ALL_TASK"),
    getAllTaskMessage("GET_ALL_TASK_MESSAGE"),
    attachDocumentTask("ATTACH_DOCUMENT_TASK"),
    getAllAttachedDocumentTask("GET_ALL_ATTACH_DOCUMENT_TASK"),
    
    
}